services:
  - type: web
    name: opencv-ui-qa-agent
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-east-1
